Class {
	#name : #LClassNames,
	#superclass : #Object,
	#category : #'LSmalltalk-Tools'
}

{ #category : #constants }
LClassNames >> arrayClassName [
	^ 'LArray'
]

{ #category : #constants }
LClassNames >> blockClassName [
	^ 'LBlock'
]

{ #category : #constants }
LClassNames >> byteArrayClassName [
	^ 'LByteArray'
]

{ #category : #constants }
LClassNames >> characterClassName [
	^ 'LChar'
]

{ #category : #constants }
LClassNames >> classClassName [
	^ 'LClass'
]

{ #category : #constants }
LClassNames >> contextClassName [
	^ 'LContext'
]

{ #category : #constants }
LClassNames >> dictionaryClassName [
	^ 'LDictionary'
]

{ #category : #constants }
LClassNames >> falseClassName [
	^ 'LFalse'
]

{ #category : #constants }
LClassNames >> integerClassName [
	^ 'LInteger'
]

{ #category : #constants }
LClassNames >> metaClassClassName [
	^ 'MetaLClass'
]

{ #category : #constants }
LClassNames >> metaObjectClassName [
	^ 'MetaLObject'
]

{ #category : #constants }
LClassNames >> methodClassName [
	^ 'LMethod'
]

{ #category : #constants }
LClassNames >> nodeClassName [
	^ 'LNode'
]

{ #category : #constants }
LClassNames >> objectClassName [
	^ 'LObject'
]

{ #category : #constants }
LClassNames >> orderedArrayClassName [
	^ 'LOrderedArray'
]

{ #category : #constants }
LClassNames >> smallIntegerClassName [
	^ 'LSmallInt'
]

{ #category : #constants }
LClassNames >> stringClassName [
	^ 'LString'
]

{ #category : #constants }
LClassNames >> symbolClassName [
	^ 'LSymbol'
]

{ #category : #constants }
LClassNames >> treeClassName [
	^ 'LTree'
]

{ #category : #constants }
LClassNames >> trueClassName [
	^ 'LTrue'
]

{ #category : #constants }
LClassNames >> undefinedClassName [
	^ 'LUndefined'
]
