Trait {
	#name : #TLClassSize,
	#category : #'LSmalltalk-Core'
}

{ #category : #constants }
TLClassSize >> instanceSizeInClass [
	^ 3
]

{ #category : #constants }
TLClassSize >> methodsInClass [
	^ 2
]

{ #category : #constants }
TLClassSize >> nameInClass [
	^ 0
]

{ #category : #constants }
TLClassSize >> parentClassInClass [
	^ 1
]

{ #category : #constants }
TLClassSize >> variablesInClass [
	^ 4
]
