Trait {
	#name : #TLNames,
	#category : #'LSmalltalk-Tools'
}

{ #category : #constants }
TLNames >> falseObjectName [
	^ 'false'
]

{ #category : #constants }
TLNames >> globalsObjectName [
	^ 'LSmalltalk'
]

{ #category : #constants }
TLNames >> metaName [
	^ 'Meta'
]

{ #category : #constants }
TLNames >> nilObjectName [
	^ 'nil'
]

{ #category : #constants }
TLNames >> startUpMethodName [
	^ 'boot'
]

{ #category : #constants }
TLNames >> trueObjectName [
	^ 'true'
]
