Trait {
	#name : #TLNames,
	#category : #'LSmalltalk-Tools'
}

{ #category : #constants }
TLNames >> arrayClassName [
	^ 'LArray'
]

{ #category : #constants }
TLNames >> blockClassName [
	^ 'LBlock'
]

{ #category : #constants }
TLNames >> byteArrayClassName [
	^ 'LByteArray'
]

{ #category : #constants }
TLNames >> characterClassName [
	^ 'LChar'
]

{ #category : #constants }
TLNames >> classClassName [
	^ 'LClass'
]

{ #category : #constants }
TLNames >> contextClassName [
	^ 'LContext'
]

{ #category : #constants }
TLNames >> dictionaryClassName [
	^ 'LDictionary'
]

{ #category : #constants }
TLNames >> falseClassName [
	^ 'LFalse'
]

{ #category : #constants }
TLNames >> falseObjectName [
	^ 'false'
]

{ #category : #constants }
TLNames >> globalsObjectName [
	^ 'LSmalltalk'
]

{ #category : #constants }
TLNames >> integerClassName [
	^ 'LInteger'
]

{ #category : #constants }
TLNames >> metaClassClassName [
	^ 'MetaLClass'
]

{ #category : #constants }
TLNames >> metaName [
	^ 'Meta'
]

{ #category : #constants }
TLNames >> metaObjectClassName [
	^ 'MetaLObject'
]

{ #category : #constants }
TLNames >> methodClassName [
	^ 'LMethod'
]

{ #category : #constants }
TLNames >> nilObjectName [
	^ 'nil'
]

{ #category : #constants }
TLNames >> nodeClassName [
	^ 'LNode'
]

{ #category : #constants }
TLNames >> objectClassName [
	^ 'LObject'
]

{ #category : #constants }
TLNames >> orderedArrayClassName [
	^ 'LOrderedArray'
]

{ #category : #constants }
TLNames >> smallIntegerClassName [
	^ 'LSmallInt'
]

{ #category : #constants }
TLNames >> smalltalkName [
	^ 'LSmalltalk'
]

{ #category : #constants }
TLNames >> startUpMethodName [
	^ 'boot'
]

{ #category : #constants }
TLNames >> stringClassName [
	^ 'LString'
]

{ #category : #constants }
TLNames >> symbolClassName [
	^ 'LSymbol'
]

{ #category : #constants }
TLNames >> treeClassName [
	^ 'LTree'
]

{ #category : #constants }
TLNames >> trueClassName [
	^ 'LTrue'
]

{ #category : #constants }
TLNames >> trueObjectName [
	^ 'true'
]

{ #category : #constants }
TLNames >> undefinedClassName [
	^ 'LUndefined'
]
